package com.coredeux.core.jdbc.service.impl;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.List;
import java.util.Map;
import java.util.UUID;

import javax.sql.DataSource;

import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.BeanPropertyRowMapper;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;

import com.coredeux.core.exceptions.CoredeuxDataAccessException;
import com.coredeux.core.exceptions.CoredeuxValidationException;
import com.coredeux.core.jdbc.testentity.SampleJdbcEntity;
import com.coredeux.core.search.SearchParams;
import com.coredeux.core.search.SearchResult;

class DefaultCoredeuxJdbcDataAccessServiceTest {

    private JdbcTemplate jdbcTemplate;
    private DefaultCoredeuxJdbcDataAccessService dataAccessService;

    @BeforeEach
    void setUp() {
        DataSource dataSource = createDataSource();
        jdbcTemplate = new JdbcTemplate(dataSource);
        jdbcTemplate.execute("drop table if exists sample_jdbc_entities");
        jdbcTemplate.execute("""
                create table sample_jdbc_entities (
                    id bigint generated by default as identity primary key,
                    name varchar(255),
                    age integer,
                    json_payload varchar(255)
                )
                """);
        dataAccessService = new DefaultCoredeuxJdbcDataAccessService(new NamedParameterJdbcTemplate(dataSource), "");
    }

    @Test
    void shouldSaveLoadUpdateRemoveAndRefreshEntity() {
        SampleJdbcEntity created = sample(null, "Alpha", 10, "one");
        String id = dataAccessService.save(created);

        assertNotNull(id);
        assertEquals(Long.valueOf(id), created.getId());

        SampleJdbcEntity loaded = dataAccessService.load(id, SampleJdbcEntity.class);
        assertEquals("Alpha", loaded.getName());
        assertEquals("one", loaded.getPayload());

        SampleJdbcEntity detachedUpdate = sample(Long.valueOf(id), "Alpha Updated", 15, "two");
        dataAccessService.update(detachedUpdate);

        SampleJdbcEntity updated = jdbcTemplate.queryForObject(
                "select id, name, age, json_payload as payload from sample_jdbc_entities where id = ?",
                BeanPropertyRowMapper.newInstance(SampleJdbcEntity.class), Long.valueOf(id));
        assertEquals("Alpha Updated", updated.getName());
        assertEquals(15, updated.getAge());

        jdbcTemplate.update("update sample_jdbc_entities set name = ? where id = ?", "Mutated", Long.valueOf(id));
        dataAccessService.refresh(detachedUpdate);
        assertEquals("Mutated", detachedUpdate.getName());

        dataAccessService.remove(detachedUpdate);
        assertTrue(jdbcTemplate.query(
                "select id, name, age, json_payload as payload from sample_jdbc_entities where id = ?",
                (rs, rowNum) -> new SampleJdbcEntity(), Long.valueOf(id)).isEmpty());
    }

    @Test
    void shouldLoadAllUsingSupportedComparatorsAndPagination() {
        persistSamples();

        SearchResult<SampleJdbcEntity> equalsResult = dataAccessService.loadAll(
                List.of(SearchParams.builder().field("name").comparator("EQUALS").value("Alpha").build()),
                SampleJdbcEntity.class, 10, 1);
        assertEquals(1, equalsResult.getResults().size());
        assertEquals(3L, equalsResult.getPagination().getTotalResults());
        assertEquals(1L, equalsResult.getPagination().getResultSize());

        SearchResult<SampleJdbcEntity> anywhereResult = dataAccessService.loadAll(
                List.of(SearchParams.builder().field("name").comparator("ANYWHERE").value("ha").build()),
                SampleJdbcEntity.class, 10, 1);
        assertEquals(1, anywhereResult.getResults().size());

        SearchResult<SampleJdbcEntity> rangeResult = dataAccessService.loadAll(
                List.of(SearchParams.builder().field("age").comparator("GREATERTHAN").value(10).build()),
                SampleJdbcEntity.class, 1, 1);
        assertEquals(1, rangeResult.getResults().size());
        assertEquals(2L, rangeResult.getPagination().getResultSize());
        assertEquals(2L, rangeResult.getPagination().getTotalPages());
    }

    @Test
    void shouldQueryWithNamedParametersAndPagination() {
        persistSamples();

        SearchResult<SampleJdbcEntity> result = dataAccessService.query(
                "select id, name, age, json_payload as payload from sample_jdbc_entities where age >= :age order by name",
                Map.of("age", 10), SampleJdbcEntity.class, 1, 1);

        assertEquals(1, result.getResults().size());
        assertEquals(3L, result.getPagination().getTotalResults());
        assertEquals(3L, result.getPagination().getResultSize());
        assertEquals(3L, result.getPagination().getTotalPages());
    }

    @Test
    void shouldSupportUnpagedOperations() {
        persistSamples();

        SearchResult<SampleJdbcEntity> result = dataAccessService.loadAll(List.of(), SampleJdbcEntity.class, -1, -1);

        assertEquals(3, result.getResults().size());
        assertEquals(-1L, result.getPagination().getCurrentPage());
        assertEquals(-1L, result.getPagination().getPageSize());
        assertNull(result.getPagination().getTotalResults());
    }

    @Test
    void shouldFailForInvalidSearchAndInvalidQueryInputs() {
        assertThrows(CoredeuxValidationException.class, () -> dataAccessService.load(null, SampleJdbcEntity.class));
        assertThrows(CoredeuxValidationException.class, () -> dataAccessService.load("1", null));
        assertThrows(CoredeuxValidationException.class, () -> dataAccessService.loadAll(
                List.of(SearchParams.builder().field("name").comparator("UNKNOWN").value("x").build()),
                SampleJdbcEntity.class, 10, 1));
        assertThrows(CoredeuxValidationException.class, () -> dataAccessService.loadAll(
                List.of(SearchParams.builder().field(" ").comparator("EQUALS").value("x").build()),
                SampleJdbcEntity.class, 10, 1));
        assertThrows(CoredeuxValidationException.class,
                () -> dataAccessService.query(" ", Map.of(), SampleJdbcEntity.class, 10, 1));
    }

    @Test
    void shouldWrapJdbcFailuresAsDataAccessExceptions() {
        assertThrows(CoredeuxDataAccessException.class, () -> dataAccessService.query(
                "select missing from sample_jdbc_entities", Map.of(), SampleJdbcEntity.class, 10, 1));
    }

    @Test
    void shouldAllowNullComparatorValuesToBeIgnored() {
        persistSamples();

        SearchResult<SampleJdbcEntity> result = assertDoesNotThrow(() -> dataAccessService.loadAll(
                List.of(SearchParams.builder().field("name").comparator("EQUALS").value(null).build()),
                SampleJdbcEntity.class, 10, 1));

        assertEquals(3, result.getResults().size());
    }

    @Test
    void shouldAdvertiseJdbcComparators() {
        assertFalse(dataAccessService.supportedComparators(SampleJdbcEntity.class).isEmpty());
        assertTrue(dataAccessService.supportedComparators(SampleJdbcEntity.class).contains("ANYWHERE"));
    }

    private void persistSamples() {
        jdbcTemplate.update("insert into sample_jdbc_entities(name, age, json_payload) values (?, ?, ?)",
                "Alpha", 10, "common");
        jdbcTemplate.update("insert into sample_jdbc_entities(name, age, json_payload) values (?, ?, ?)",
                "Beta", 20, "two");
        jdbcTemplate.update("insert into sample_jdbc_entities(name, age, json_payload) values (?, ?, ?)",
                "Gamma", 30, "common");
    }

    private SampleJdbcEntity sample(Long id, String name, Integer age, String payload) {
        SampleJdbcEntity entity = new SampleJdbcEntity();
        entity.setId(id);
        entity.setName(name);
        entity.setAge(age);
        entity.setPayload(payload);
        return entity;
    }

    private DataSource createDataSource() {
        JdbcDataSource dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:coredeux_jdbc_" + UUID.randomUUID() + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1");
        dataSource.setUser("sa");
        dataSource.setPassword("");
        return dataSource;
    }
}
