spring:
  application:
    name: coredeux-spring-boot-demo
  datasource:
    url: jdbc:postgresql://${COREDEUX_DEMO_DB_HOST:localhost}:${COREDEUX_DEMO_DB_PORT:5432}/${COREDEUX_DEMO_DB_NAME:coredeux_oss}
    driver-class-name: org.postgresql.Driver
    username: ${COREDEUX_DEMO_DB_USER:postgres}
    password: ${COREDEUX_DEMO_DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    mongodb:
      uri: mongodb://${COREDEUX_DEMO_MONGO_HOST:localhost}:${COREDEUX_DEMO_MONGO_PORT:27017}/${COREDEUX_DEMO_MONGO_DB:coredeux_oss}
    redis:
      host: ${COREDEUX_DEMO_REDIS_HOST:localhost}
      port: ${COREDEUX_DEMO_REDIS_PORT:6379}
  elasticsearch:
    uris: http://${COREDEUX_DEMO_ELASTICSEARCH_HOST:localhost}:${COREDEUX_DEMO_ELASTICSEARCH_PORT:9200}

coredeux:
  data-access-service: postgresCoredeuxJpaDataAccessService
  entities:
    config-location: classpath:coredeux-entities.yml
  import:
    default-parser: text
  export:
    default-format: TEXT
    log:
      default-service: defaultCoredeuxExportLogService
    storage:
      default-service: databaseCoredeuxExportStorageService
      filesystem:
        base-directory: ${COREDEUX_EXPORT_FILESYSTEM_BASE_DIRECTORY:${java.io.tmpdir}/coredeux-export}
    worker:
      enabled: true
      max-parallel: 2
      delay-ms: 3000

logging:
  level:
    com.coredeux: INFO

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha
