global com.coredeux.core.registry.CoredeuxComponentRegistry componentRegistry;

rule "sample-rule"
when
    $context : com.coredeux.drl.model.RuleContext(method == "sample-rule")
then
    com.coredeux.spring.boot.autoconfigure.drl.SampleService sampleService =
            componentRegistry.getComponent("sampleService",
                    com.coredeux.spring.boot.autoconfigure.drl.SampleService.class);
    $context.setOutput(sampleService.message());
    $context.setMessage(sampleService.message());
end
