package com.coredeux.drl.service;

import com.coredeux.drl.cache.CompiledDRLRule;
import com.coredeux.drl.model.RuleContext;

/**
 * Runtime service for executing compiled or ad hoc DRL rules.
 *
 * <p>The service resolves rules by identifier, compiles caller-provided DRL
 * when requested, and updates the supplied {@link RuleContext} with execution
 * results.
 */
public interface DRLService {

    /**
     * Resolves, compiles, caches, and executes the rule identified by the given
     * rule id.
     *
     * @param ruleId the rule identifier used by the configured source resolver
     * @param context the execution context and fact carrier
     */
    <T> void execute(String ruleId, RuleContext<T> context);

    /**
     * Compiles the supplied DRL source, stores the compiled rule base under the
     * given rule id, and executes it immediately.
     *
     * @param ruleId the cache key to use for the compiled rule base
     * @param source the DRL source text to compile
     * @param context the execution context and fact carrier
     */
    <T> void execute(String ruleId, String source, RuleContext<T> context);

    /**
     * Compiles and executes the supplied DRL source without consulting a source
     * resolver or storing the compiled result in the cache.
     *
     * @param source the DRL source text to compile
     * @param context the execution context and fact carrier
     */
    <T> void executeSource(String source, RuleContext<T> context);

    /**
     * Clears all cached compiled rule bases.
     */
    void purgeCache();

    /**
     * Removes a single cached compiled rule base.
     *
     * @param ruleId the cache key to remove
     */
    void purgeCache(String ruleId);

    /**
     * Checks whether a compiled rule base is currently cached for the rule id.
     *
     * @param ruleId the cache key to check
     * @return {@code true} if a compiled rule base is present in the cache
     */
    boolean isCached(String ruleId);
    
    /**
     * Resolves the DRL source for the supplied rule id, compiles it, and stores
     * the compiled rule base in the runtime cache without executing it.
     *
     * <p>Use this method to warm the cache during application startup, after a
     * rule has been added to an external store, or after a previously cached
     * rule has been purged. Later calls to {@link #execute(String, RuleContext)}
     * can reuse the cached compiled form instead of resolving and compiling the
     * same rule on first execution.
     *
     * @param ruleId the rule identifier to resolve through the configured source
     *        resolver and use as the cache key
     */
    void compileAndCache(String ruleId);
    
    /**
     * Compiles the supplied DRL source and stores the compiled rule base in the
     * runtime cache under the supplied rule id without executing it.
     *
     * <p>Use this method when the caller already has the DRL source text, for
     * example after reading a rule from a database, object storage, or a
     * developer tooling endpoint. The source resolver is not consulted.
     *
     * @param ruleId the cache key to associate with the compiled rule base and
     *        the label used in compilation error messages
     * @param source the DRL source text to compile and cache
     */
    void compileAndCache(String ruleId, String source);
    
    /**
     * Resolves the DRL source for the supplied rule id and compiles it into an
     * executable rule bundle without storing it in the runtime cache or firing
     * any rules.
     *
     * <p>Use this method when a caller needs to validate or inspect a rule
     * before deciding whether it should be cached or executed. Later execution
     * is the caller's responsibility unless the compiled result is passed into a
     * cache-aware flow.
     *
     * @param ruleId the rule identifier to resolve through the configured source
     *        resolver and use in compilation error messages
     * @return the compiled rule bundle, including the KIE base and detected
     *         runtime metadata
     */
    CompiledDRLRule compile(String ruleId);
    
    /**
     * Compiles the supplied DRL source into an executable rule bundle without
     * consulting the source resolver, storing it in the runtime cache, or firing
     * any rules.
     *
     * <p>Use this method for compile-only validation of caller-provided source,
     * such as source read from a database, file, object storage, or generated by
     * developer tooling.
     *
     * @param ruleId the label used in compilation error messages
     * @param drl the DRL source text to compile
     * @return the compiled rule bundle, including the KIE base and detected
     *         runtime metadata
     */
    CompiledDRLRule compile(String ruleId, String drl);
}
